collections:
  entries:
      output: true
      permalink: /entries/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: update
  - scope:
      path: ""
      type: entries
    values:
      layout: entry
      sort: url

exclude: ['Gemfile','Gemfile.lock']

gems:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-paginate
  - jekyll-sitemap

google_site_verification: QfXW9ibW_gwrtsViUn9usf-eQqU5OT45JV1aBm-cMBE

logo: /assets/images/david.jpg

#paginate: 5
#paginate_path: "/posts/page-:num/"

permalink: /posts/:title

social:
    name: David Rodenas
    links:
      - https://twitter.com/drpicox
      - https://github.com/drpicox

title: "David Rodenas' Home"

twitter:
  username: drpicox

